version: '3.9'

services:
  api:
    build:
      context: ./
      dockerfile: api/Dockerfile
    ports:
      - "5051:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - maple-net
    depends_on:
      - scraper

  scraper:
    build:
      context: ./
      dockerfile: scraper/Dockerfile 
    networks:
      - maple-net

networks:
  maple-net:
    driver: bridge
